wandb_version: 1

name:
  desc: null
  value: E-C
threshold:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709416947.016805
    t:
      1:
      - 5
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
